[workspace]
authors = ["alix559 <alixjcob559@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly/", "conda-forge"]
name = "material_grammar"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
nbdev = ">=2.4.5,<3"
quarto = ">=1.7.33,<2"
jupyter = ">=1.1.1,<2"
mojo = ">=25.6.0.dev2025082605,<26"
ase = ">=3.26.0,<4"
pymatgen = ">=2025.6.14,<2026"
nglview = ">=3.1.4,<4"
ipywidgets = ">=8.1.7,<9"
mp-api = ">=0.45.8,<0.46"
phonopy = ">=2.43.1,<3"
